[package]
name = "hamurabi"
version = "0.1.0"
authors = ["beyonddream <43626691+beyonddream@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
text_io = "0.1.8"
